config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :lectures do
    resources :comments
    #/lectures/download_file
    collection do
     
    end
    member do
      get :download_file
      get :like_or_unlike
      get :spam_lec
    end
    
  end
  resources :courses
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "courses#index"
end

app/models/lecture.rb
class Lecture < ApplicationRecord
    acts_as_votable
    #lecture created by only user
    belongs_to :user 

    #lecture belongs_to one course
    belongs_to :course

    #lecture has many comments
    has_many :comments
    has_many :users, through: :comments

    #upload image
    mount_uploader :attachment , AttachmentUploader

    #many to many relation [flag as spam]
    has_and_belongs_to_many :users

    validates :content, presence: true
end

app/controllers/lectures_controller.rb
class LecturesController < InheritedResources::Base
  before_action :authenticate_user!
 
  def new
    @lecture = Lecture.new
    authorize! :create, @lecture
  end

  def create
    @user_id= lecture_params['user_id']
    if( @user_id.to_i == current_user.id )
      @lecture = Lecture.create(lecture_params)
     
      respond_to do |format|
        if @lecture.save
          format.html { redirect_to lectures_url, notice: 'Lecture created successfully ' }
        else
          format.html { redirect_to lectures_url, notice: 'You cannot create lecture' }
        end
       end     
    else
        respond_to do |format|
          format.html { redirect_to lectures_url, notice: 'You cannot create lecture' }
        end
    end
  end
  
  def edit
    @lecture = Lecture.find(params[:id])
    authorize! :edit, @lecture
  end

  def destory
    authorize! :destory, @lecture
  end
  def download_file
    @lecture = Lecture.find(params[:id])
    send_file(@lecture.attachment.path,
          :disposition => 'attachment')
  end

  def like_or_unlike
    @lecture = Lecture.find(params[:id])
    if (!current_user.voted_for? @lecture)
      @lecture.liked_by current_user
      redirect_to @lecture
    else
      @lecture.unliked_by current_user
      redirect_to @lecture
    end  
  end
  
  def spam_lec
    @lecture = Lecture.find(params[:id])
   
    unless @lecture.users.where(id: current_user.id).first
      @lecture.users << current_user 
    end

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to lectures_url, notice: 'You flag lecture as a spam ' }
      else
        
      end
    end
    
  end
  
  private
   
    def lecture_params
      params.require(:lecture).permit(:content, :attachment, :user_id, :course_id)
    end


end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, local: true) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.cktext_area :content, id: :lecture_content %>
  </div>



  <div class="field">
  <%= form.label :attachment %><br>
  <%= form.file_field :attachment %>
  </div>

  <div class="field">
    <%= form.hidden_field :course_id, :value => params[:course_id] %>
  </div>
 
  <div class="field">
  <%= form.hidden_field :user_id, :value => params[:user_id] %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Course</th>
      <th>User</th>
      <th>Attachment</th>
      <th>Like Or Unlike Lecture</th>
      <th>Spam Lecture</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= raw(lecture.content) %></td>
        <td><%= lecture.course.title %></td>
        <td><%= lecture.user.name %></td>
        <td><%= link_to "Download", download_file_lecture_path(lecture) %></td>
        <% if (! current_user.voted_for? lecture) %>
        <td><%= link_to "like", like_or_unlike_lecture_path(lecture) %></td>
        <% else %>
        <td><%= link_to "unlike", like_or_unlike_lecture_path(lecture) %></td>
        <% end %>
        <% if !current_user.lectures.where(id: lecture.id ).first %>
        <td><%= link_to 'Spam a Lecture', spam_lec_lecture_path(lecture) %></td>
        <% else %>
        <td></td>
        <% end %>
        <td>
        <%= link_to 'Show', lecture %>
        <% if ( can? :update, Lecture ) && ( current_user.id == lecture.user.id ) %>
        <%= link_to 'Edit', edit_lecture_path(lecture,user_id: lecture.user.id ,course_id: lecture.course.id) %>
        <%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
        </td>
       
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= raw(@lecture.content) %>
</p>

<p>
  <strong>Attachment:</strong>
  <%= link_to "Download", download_file_lecture_path(@lecture) %>
</p>

<p>
  <strong>Course:</strong>
  <%= @lecture.course.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @lecture.user.name %>
  
</p>

<div class ="container">
  <h2>Comments</h2>
  <h3 class="subtitle is-5"><strong><%= @lecture.comments.count %></strong> Comments</h3>
  <h3 class="subtitle is-5"><strong><%= @lecture.votes_for.size %></strong> Likes
  <% if (! current_user.voted_for? @lecture) %>
        <%= link_to "like", like_or_unlike_lecture_path(@lecture) %>
        <% else %>
        <%= link_to "unlike", like_or_unlike_lecture_path(@lecture) %>
  <% end %>
  </h3>
  <% @lecture.comments.each do |comment| %>
    
    <div class="comment">
    <%= image_tag comment.user.avatar, class: 'my_image_size' %>
    <p>
      <strong>Commenter:</strong>
      <%= comment.user.name%>
    </p>
    <p>
      <strong>Comment:</strong>
      <%= comment.content %>
    </p>
    
    
    </div>
    <br>
    <br>
  <% end %>
</div>
<div class="container">
  <h2>Add Comment</h2>
  <%= render 'comments/form' %>
</div>

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>