config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :lectures do
    resources :comments
    #/lectures/download_file
    collection do
     
    end
    member do
      get :download_file
      get :like_or_unlike
      get :spam_lec
    end
    
  end
  resources :courses
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "courses#index"
end

app/controllers/courses_controller.rb
class CoursesController < InheritedResources::Base
  before_action :authenticate_user!

  def new
    @course=Course.new
    authorize! :create, @course
  end

  def create
    @course = Course.new(course_params)
    @course.user = current_user
    if @course.save
      redirect_to @course
    else
      render 'new'
    end
  end

  def edit
    @course = Course.find(params[:id])
    authorize! :update, @course
  end 
  
  def destory
    authorize! :destory, @course
  end  
  
  private

    def course_params
      params.require(:course).permit(:title)
    end

    

end

app/helpers/courses_helper.rb
module CoursesHelper
    def users_for_select
        User.all.collect { |m| [m.name, m.id] }
      end
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :course_title %>
  </div>

  



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>
<%= flash[:alert] %>
<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>User</th>
      <th>Actions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.user.name %></td>
        <td><%= link_to 'Show', course %>
        <% if ( can? :update, Course ) && ( current_user.id == course.user.id ) %>
  
        <%= link_to 'Add new Lecture', new_lecture_path(user_id: course.user.id ,course_id: course.id)  %>
        <%= link_to 'Edit', edit_course_path(course) %>
        <%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %>
        
       
        
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if ( can? :update, Course )  %>
<%= link_to 'New Course', new_course_path %>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @course.user.name %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>